import type { AuditReport, Grade, Lang, RuleReportEntry } from '../types.js';
import { DIMENSION_LABELS, DIMENSIONS } from '../rules/index.js';
import { getEvidence } from '../evidence/papers.js';
import { REPO_URL } from '../version.js';

const GRADE_LABEL: Record<Grade, { en: string; zh: string }> = {
  excellent: { en: 'Excellent', zh: '优秀' },
  good: { en: 'Good', zh: '良好' },
  fair: { en: 'Needs work', zh: '一般' },
  poor: { en: 'At risk', zh: '较差' },
};

const STATUS_LABEL = {
  pass: { en: 'Pass', zh: '通过' },
  warn: { en: 'Warn', zh: '警告' },
  fail: { en: 'Fail', zh: '未通过' },
  na: { en: 'N/A', zh: '不适用' },
} as const;

const UI = {
  docTitle: { en: 'GEODoctor — AI Search Health Report', zh: 'GEODoctor — AI 搜索体检报告' },
  subtitle: {
    en: 'Can AI see you? An evidence-backed GEO (Generative Engine Optimization) checkup.',
    zh: 'AI 能看见你吗?一份有论文依据的 GEO(生成式引擎优化)体检。',
  },
  score: { en: 'GEO Score', zh: 'GEO 总分' },
  pages: { en: 'Pages sampled', zh: '抽样页面' },
  generated: { en: 'Generated', zh: '生成时间' },
  dimensions: { en: 'Dimension scores', zh: '维度得分' },
  details: { en: 'Full checkup results', zh: '完整体检结果' },
  why: { en: 'Why it matters', zh: '为什么重要' },
  finding: { en: 'Finding', zh: '检查所见' },
  fix: { en: 'Prescription', zh: '处方' },
  evidence: { en: 'Evidence', zh: '证据' },
  passed: { en: 'passed', zh: '通过' },
  warned: { en: 'warnings', zh: '警告' },
  failed: { en: 'failed', zh: '未通过' },
  footer: {
    en: 'Generated by GEODoctor — the open-source GEO agent. Every rule cites public research.',
    zh: '由开源 GEO Agent「GEODoctor」生成——每条规则均引用公开研究。',
  },
  methodology: { en: 'Scoring methodology', zh: '评分方法论' },
} as const;

export function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function scoreHue(score: number): string {
  if (score >= 85) return '#15803d';
  if (score >= 70) return '#0f766e';
  if (score >= 50) return '#b45309';
  return '#b91c1c';
}

function statusChip(entry: RuleReportEntry, lang: Lang): string {
  const colors = { pass: '#15803d', warn: '#b45309', fail: '#b91c1c', na: '#6b7280' } as const;
  const bg = { pass: '#f0fdf4', warn: '#fffbeb', fail: '#fef2f2', na: '#f3f4f6' } as const;
  const label = STATUS_LABEL[entry.status][lang];
  return `<span class="chip" style="color:${colors[entry.status]};background:${bg[entry.status]}">● ${label}</span>`;
}

function evidenceLinks(entry: RuleReportEntry): string {
  return entry.evidence
    .map((id) => {
      const ev = getEvidence(id);
      if (!ev) return '';
      return `<a href="${escapeHtml(ev.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(ev.source)}</a>`;
    })
    .filter(Boolean)
    .join(' · ');
}

function ruleRow(entry: RuleReportEntry, lang: Lang): string {
  const fix = entry.fix
    ? `<p class="fix"><strong>${UI.fix[lang]}:</strong> ${escapeHtml(entry.fix[lang])}</p>`
    : '';
  return `
    <div class="rule">
      <div class="rule-head">
        ${statusChip(entry, lang)}
        <h4>${escapeHtml(entry.name[lang])}</h4>
        <code>${escapeHtml(entry.id)}</code>
      </div>
      <p class="finding">${escapeHtml(entry.finding[lang])}</p>
      ${fix}
      <p class="meta"><span>${UI.why[lang]}:</span> ${escapeHtml(entry.why[lang])}</p>
      <p class="meta"><span>${UI.evidence[lang]}:</span> ${evidenceLinks(entry)}</p>
    </div>`;
}

/** Render the self-contained shareable HTML report. */
export function renderHtml(report: AuditReport, lang: Lang): string {
  const hue = scoreHue(report.totalScore);
  const grade = GRADE_LABEL[report.grade][lang];
  const deg = Math.round((report.totalScore / 100) * 360);

  const dimBars = report.dimensions
    .map((dim) => {
      const label = DIMENSION_LABELS[dim.dimension][lang];
      const color = scoreHue(dim.score);
      return `
      <div class="dim">
        <div class="dim-label"><span>${escapeHtml(label)}</span><strong style="color:${color}">${dim.score}</strong></div>
        <div class="dim-track"><div class="dim-fill" style="width:${dim.score}%;background:${color}"></div></div>
        <div class="dim-counts">${dim.passed} ${UI.passed[lang]} · ${dim.warned} ${UI.warned[lang]} · ${dim.failed} ${UI.failed[lang]}</div>
      </div>`;
    })
    .join('');

  const sections = DIMENSIONS.map((dimension) => {
    const entries = report.results.filter((r) => r.dimension === dimension);
    const sorted = [...entries].sort(
      (a, b) => ({ fail: 0, warn: 1, na: 2, pass: 3 })[a.status] - ({ fail: 0, warn: 1, na: 2, pass: 3 })[b.status],
    );
    return `
    <section>
      <h3>${escapeHtml(DIMENSION_LABELS[dimension][lang])}</h3>
      ${sorted.map((e) => ruleRow(e, lang)).join('')}
    </section>`;
  }).join('');

  const pageList = report.pagesAudited
    .map((p) => `<li><a href="${escapeHtml(p)}" target="_blank" rel="noopener noreferrer">${escapeHtml(p)}</a></li>`)
    .join('');

  return `<!doctype html>
<html lang="${lang === 'zh' ? 'zh-CN' : 'en'}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(UI.docTitle[lang])} · ${escapeHtml(report.finalUrl)}</title>
<style>
  :root {
    --paper: #faf9f7; --card: #ffffff; --ink: #1c1917; --muted: #78716c;
    --line: #e7e5e4; --accent: #0f766e;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; background: var(--paper); color: var(--ink);
    font: 15px/1.65 ui-sans-serif, system-ui, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif;
    -webkit-font-smoothing: antialiased;
  }
  .wrap { max-width: 880px; margin: 0 auto; padding: 48px 24px 64px; }
  header.brand { display: flex; align-items: baseline; gap: 10px; margin-bottom: 6px; }
  header.brand h1 { font-family: Georgia, "Songti SC", serif; font-size: 26px; margin: 0; letter-spacing: -0.02em; }
  header.brand .beat { color: var(--accent); }
  .subtitle { color: var(--muted); margin: 0 0 28px; font-size: 14px; }
  .hero {
    background: var(--card); border: 1px solid var(--line); border-radius: 16px;
    padding: 32px; display: grid; grid-template-columns: 180px 1fr; gap: 32px; align-items: center;
    box-shadow: 0 1px 2px rgb(0 0 0 / 0.03), 0 8px 24px rgb(0 0 0 / 0.04);
  }
  .ring {
    width: 168px; height: 168px; border-radius: 50%;
    background: conic-gradient(${hue} ${deg}deg, #efedeb ${deg}deg);
    display: grid; place-items: center;
  }
  .ring-inner {
    width: 128px; height: 128px; border-radius: 50%; background: var(--card);
    display: grid; place-items: center; text-align: center;
  }
  .ring-inner .num { font-size: 42px; font-weight: 700; color: ${hue}; line-height: 1; }
  .ring-inner .grade { font-size: 13px; color: var(--muted); margin-top: 4px; }
  .hero h2 { margin: 0 0 4px; font-size: 18px; word-break: break-all; }
  .hero .facts { color: var(--muted); font-size: 13px; margin: 0 0 16px; }
  .dim { margin-bottom: 14px; }
  .dim-label { display: flex; justify-content: space-between; font-size: 13.5px; margin-bottom: 4px; }
  .dim-track { height: 8px; background: #efedeb; border-radius: 99px; overflow: hidden; }
  .dim-fill { height: 100%; border-radius: 99px; }
  .dim-counts { font-size: 11.5px; color: var(--muted); margin-top: 3px; }
  section { margin-top: 36px; }
  section > h3 {
    font-family: Georgia, "Songti SC", serif; font-size: 19px; margin: 0 0 14px;
    padding-bottom: 8px; border-bottom: 2px solid var(--ink);
  }
  .rule {
    background: var(--card); border: 1px solid var(--line); border-radius: 12px;
    padding: 16px 18px; margin-bottom: 10px;
  }
  .rule-head { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }
  .rule-head h4 { margin: 0; font-size: 15px; }
  .rule-head code { font-size: 11px; color: var(--muted); background: #f5f4f2; padding: 2px 6px; border-radius: 6px; }
  .chip { font-size: 12px; font-weight: 600; padding: 3px 10px; border-radius: 99px; white-space: nowrap; }
  .finding { margin: 10px 0 0; }
  .fix { margin: 8px 0 0; padding: 10px 12px; background: #f0fdfa; border-left: 3px solid var(--accent); border-radius: 0 8px 8px 0; }
  .meta { margin: 8px 0 0; font-size: 12.5px; color: var(--muted); }
  .meta span { font-weight: 600; }
  .meta a { color: var(--accent); }
  .pages { margin-top: 36px; font-size: 13px; color: var(--muted); }
  .pages ul { margin: 6px 0 0; padding-left: 18px; }
  .pages a { color: var(--accent); word-break: break-all; }
  footer {
    margin-top: 48px; padding-top: 20px; border-top: 1px solid var(--line);
    font-size: 13px; color: var(--muted); display: flex; justify-content: space-between; gap: 16px; flex-wrap: wrap;
  }
  footer a { color: var(--accent); font-weight: 600; text-decoration: none; }
  @media (max-width: 640px) { .hero { grid-template-columns: 1fr; justify-items: center; text-align: center; } }
</style>
</head>
<body>
  <div class="wrap">
    <header class="brand"><h1>🩺 GEODoctor</h1><span class="beat">▚▞</span></header>
    <p class="subtitle">${escapeHtml(UI.subtitle[lang])}</p>

    <div class="hero">
      <div class="ring"><div class="ring-inner">
        <div><div class="num">${report.totalScore}</div><div class="grade">${escapeHtml(UI.score[lang])} · ${escapeHtml(grade)}</div></div>
      </div></div>
      <div>
        <h2>${escapeHtml(report.finalUrl)}</h2>
        <p class="facts">${UI.generated[lang]}: ${escapeHtml(report.generatedAt.slice(0, 19).replace('T', ' '))} UTC · ${UI.pages[lang]}: ${report.pagesAudited.length} · v${escapeHtml(report.version)}</p>
        ${dimBars}
      </div>
    </div>

    <section><h3>${escapeHtml(UI.details[lang])}</h3></section>
    ${sections}

    <div class="pages">
      <strong>${escapeHtml(UI.pages[lang])}</strong>
      <ul>${pageList}</ul>
    </div>

    <footer>
      <span>${escapeHtml(UI.footer[lang])}</span>
      <span><a href="${REPO_URL}" target="_blank" rel="noopener noreferrer">⭐ GEODoctor</a> · <a href="${REPO_URL}/blob/main/docs/methodology.md" target="_blank" rel="noopener noreferrer">${escapeHtml(UI.methodology[lang])}</a></span>
    </footer>
  </div>
</body>
</html>`;
}
